- title: Capacitaciones y Talleres
  icon: group
  description: "Te enseñamos a programar desde cero a través de capacitaciones y talleres _in-situ_. Y también hacemos _inception_: te enseñamos sobre cómo enseñar programación."

- title: Automatización de tareas
  icon: cogs
  description: "Te ofrecemos herramientas on-line para que puedas ser un docente de programación más eficiente. Gracias a nuestras correcciones automatizadas y consolas de seguimiento del curso, podés hacer más con menos esfuerzo."

- title: Edición y personalización
  icon: book
  description: "Te ayudamos a personalizar el contenido didáctico de Mumuki, utilizando nuestras herramientas de edición. Y por si fuera poco, podés crear tus propios ejercicios y apuntes: vos elegís qué enseñar y cómo."
